### ISSUE TITLE
num-processes: integer end argument expected, got str

### ISSUE THREAD

**Issue by stas** [jmvrbanac/Specter#52]
Looks like `--num-processes` argument doesn't get converted to a number.

**Comment by jmvrbanac** [comment]
Woops! Sorry about the issue spam. Accidentally, closed the bug before it was released.

**Comment by stas** [comment]
Awesome stuff! :+1: 

Thanks a lot for the quick response.

**Comment by jmvrbanac** [comment]
Sorry for the delay on releasing this. I haven't cut a new release yet as I wanted to address Issue #49 before I made a new release. Anyhow, I just figured out the issue and submitted an upstream PR to fix the issue. As a result, I'm planning on cutting a release this next weekend (April 4th); sooner if the Pynsive maintainer releases my fix in the next couple days. Thanks!

**Comment by stas** [comment]
No worries @jmvrbanac 
We monkey-patched our runner to work with it.

**Comment by jmvrbanac** [comment]
@stas 0.2.1 has been released with this fix in it. Let me know how it works for you!

**Comment by stas** [comment]
:fireworks:
