### ISSUE TITLE
Test case definitions including SSH connections

### ISSUE THREAD

**Issue by ghost** [jmvrbanac/Specter#60]
Hi,
    You responded to my original problem query yesterday. I was using my corporate handle. I can now write test code with the Specter library, thanks to your comment. As I mentioned, my background is in Ruby, C and C#. 
    You have defined Specter's feature set really good. On top of them, I am looking for these additional requirements:
#1 Ability to open a SSH connection to a remote device (rackmount server, rackmount/desktop workstation pc, switch, router etc). 
    I do not see a reference for support of SSH or Telnet connections in Specter READMEs. Is this something that can be added up in the future as a new feature (using Python's pty module)? This may need something like the use of spawn() in package pexpect. More information on pexpect package can be obtained at this link: http://pexpect.sourceforge.net/pexpect.html. 
#2 Ability to define test cases in a test suite. 
    I understand each test case is defined as a derived class of class Spec. And nesting is supported in Specter (class within class) and Python can do it. 
    Would it be possible to reference each test case as a module in a package (instead of a class) and each test suite as the package of modules? May be, this model may help to define test suites easier. This is obviously debatable but can be a key enhancement.
#3 I think the assertions part of the library is already defined pretty good. I will test them for various test situations. 
#4 I would think the RegExp module of Python should be usable within the expect() method. Are there restrictions on shell meta-characters that you may know of as applicable to the expect() method? I will check these out and update the same thread if I see issues. 
Thanks,
Mihir Calahasti

**Comment by jmvrbanac** [comment]
Btw, if want to see some Specter tests in action on a couple of other projects, take a look at:
https://github.com/jmvrbanac/requests-cloud-auth
https://github.com/jmvrbanac/alchemize
https://github.com/jmvrbanac/lplight

There are a number of other folks that use Specter on their projects, but I figured I would just mention a couple of examples from smaller projects.

1 - I'm not sure I see the benefit in bundling ssh functionality within Specter. In Python, the majority of people who need to interact with nodes via SSH use [Paramiko](http://docs.paramiko.org/en/1.15/). If you're looking for dealing with processes on your current machine, then I would look into the Python subprocess module.

2 - Yes. If you look at some of the project examples mentioned above, you'll see that I tend to organize most of my tests within independent python models and sub-packages.

4 - I don't know. If there is a restriction, I would imagine it would be with Python itself.

**Comment by jmvrbanac** [comment]
Going to close this for now. If you believe this is still an issue, please reopen.
