### ISSUE TITLE
'--select-tests' runs all tests that match partially to the string passed in

### ISSUE THREAD

**Issue by chellygel** [jmvrbanac/Specter#69]
When a test is run with '--select-tests' all tests that are similar to the string passed in will be run.

EX:
If you have a tests with the names:

- apples
- apples_and_cinnamon

Then execute specter with ```--select-tests 'apples_and_cinnamon'```
Specter will also execute the "apples" because it's looking for the test name in a list that is only a string.
This results in it essentially doing ```if string in string``` instead of the expected ```if string in list```.

**Comment by jmvrbanac** [comment]
Updated the issue with a little clarification.
